apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations: #Both "name" and "server" are used to cover all use cases
  - name: in-cluster
    namespace: 'default'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/PauloJFCabral/gitops-masterclass-appprojects-template
